Initial import.
elasticio/ldap-component pull request #1
Opened 2017-12-05 15:04 UTC by jhorbulyk

@fredddy123

2017-12-05 15:16 UTC, fredddy123 requested changes

2017-12-05 15:16 UTC, fredddy123 commented on dummy.spec.js
> +'use strict';
why there is this file?

2017-12-05 15:20 UTC, drobiazko commented on IntegrationTest.js
> +      const emitter = new TestEmitter();
A bit more nice approach would be to use a spy, for example http://sinonjs.org/.

````js
const self = {
    emit: sinon.spy()
}
...

await search.process.call(self, msg, cfg, null);

...


self.emit.getCall(0).args[0].should.be.eq('data')
self.emit.getCall(0).args[1].body.should.be.deep.eq(BLA)
````

2017-12-05 15:22 UTC, jhorbulyk commented on dummy.spec.js
> +'use strict';
It's so that you can add a [test script](https://github.com/elasticio/ldap-component/blob/initial-write/package.json#L16) in the `package.json` file without `npm test` failing.  I suppose that it is nice to have the test script for the sake of the automated build even when you have components where automated unit testing doesn't make much sense.

2017-12-05 15:28 UTC, jhorbulyk commented on IntegrationTest.js
> +      const emitter = new TestEmitter();
Good to know that this is a possibility.  This has been [a pattern that I have been using as I write components](https://github.com/elasticio/platform/pull/52/files#diff-df7bb7cfac24a83da21062f0d310422bR46) so it is good to know that I can switch to a cleaner alternative in the future.

2017-12-05 15:29 UTC, jhorbulyk commented on IntegrationTest.js
> +      const emitter = new TestEmitter();
@drobiazko Should I implement this change now?

2017-12-05 15:52 UTC, fredddy123 approved these changes

2017-12-05 16:08 UTC, drobiazko commented on IntegrationTest.js
> +      const emitter = new TestEmitter();
if you don't mind let's switch to a better alternative here and rephrase the `Create libraries to facilitate unit testing` paragraph

2017-12-05 16:09 UTC, drobiazko commented on IntegrationTest.js
> +      const emitter = new TestEmitter();
btw you can find some examples of `sinon.js` usage in https://github.com/elasticio/microsoft-dynamics-nav-2015

2017-12-06 08:58 UTC, drobiazko commented on spec-integration/IntegrationTest.js
> +      expect(emitter.emit.withArgs('data').callCount).to.be.equal(4);
In stead of expecting the proper call count I would rather write 4 expectations each asserting the exact payload

2017-12-06 10:02 UTC, jhorbulyk commented on spec-integration/IntegrationTest.js
> +      expect(emitter.emit.withArgs('data').callCount).to.be.equal(4);
I don't want to write too many strict assertions for an integration test as the data in the system connected to during the tests may change.

2017-12-06 10:06 UTC, drobiazko requested changes

2017-12-06 10:06 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
Why do we need the dummy spec?

2017-12-06 10:06 UTC, drobiazko commented on spec-integration/IntegrationTest.js
> +      expect(emitter.emit.withArgs('data').callCount).to.be.equal(4);
The proper approach would be to start your tests on a clean state. For example before running the test you could insert some objects and be sure that you get exactly them in your assertions.

2017-12-06 10:46 UTC, jhorbulyk commented on spec-integration/IntegrationTest.js
> +      expect(emitter.emit.withArgs('data').callCount).to.be.equal(4);
That would be ideal but isn't particularly feasible at the moment.

2017-12-06 10:46 UTC, jhorbulyk commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
It's so that you can add a [test script](https://github.com/elasticio/ldap-component/blob/initial-write/package.json#L16) in the `package.json` file without `npm test` failing.  I suppose that it is nice to have the test script for the sake of the automated build even when you have components where automated unit testing doesn't make much sense.

2017-12-06 11:26 UTC, drobiazko commented on spec-integration/IntegrationTest.js
> +      expect(emitter.emit.withArgs('data').callCount).to.be.equal(4);
ok

2017-12-06 11:27 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
you don't need it as you can reconfigure what to do on `npm test`. For example check this out https://github.com/elasticio/outlook/blob/master/package.json#L16

You can let `npm test` run your integration tests only

2017-12-06 12:25 UTC, jhorbulyk commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
I can't have `npm test` run my integration tests as I can't securely provide the credentials to circle.ci.  The alternative is that the `npm test` command is an echo statement.  Is that preferable to having a dummy test?

2017-12-06 12:28 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
how is your integration test started at the moment and where? CircleCI or Travis?

2017-12-06 12:30 UTC, jhorbulyk commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
I can trigger integration test runs to run on Travis.  Should I set that up as part of this PR?

2017-12-06 12:32 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
no, I just want to know how your integration test is started and when?

2017-12-06 12:34 UTC, jhorbulyk commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
`npm run integration-test` [here](https://github.com/elasticio/ldap-component/blob/initial-write/package.json#L17)

2017-12-06 12:37 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
Look in your `package.json` you have:

````
"scripts": {
   "pretest": "eslint verifyCredentials.js lib spec spec-integration --fix",
   "test": "mocha spec",
   "integration-test": "mocha spec-integration"
}
````

you specified `npm test` to run mocha in `spec` directory but the only test in this directory is dummy test.

Why don't you just write:

````
"scripts": {
   "pretest": "eslint verifyCredentials.js lib spec spec-integration --fix",
   "test": "mocha spec-integration"
}
````

2017-12-06 12:37 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
and remove `spec/dummy.spec.js`

2017-12-06 12:39 UTC, jhorbulyk commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
If I wrote `"test": "mocha spec-integration"` then the build would fail on Circle.ci.  And when we discussed this subject previously, you expressed a desire for all of our repositories to be able to be built on circle.ci.

2017-12-06 12:51 UTC, drobiazko commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
can I see your build? I don't see it on our circleci

2017-12-06 12:55 UTC, zubairov commented on spec/dummy.spec.js
> +const expect = require('chai').expect;
Guys, as this is an open sourced component I would suggest to use travis instead of circle here - it will give possibility to run tests on PRs even for ppl outside of our org

2017-12-06 15:31 UTC, drobiazko approved these changes

2017-12-06 15:32 UTC, merged